# Generated by Django 4.2 on 2025-05-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='cv_path',
        ),
        migrations.AddField(
            model_name='candidat',
            name='cv',
            field=models.FileField(blank=True, help_text='Format PDF recommandé', null=True, upload_to='cvs/', verbose_name='CV du candidat'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'entreprise"),
        ),
    ]
