# Generated by Django 4.2 on 2025-05-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pme', '0002_remove_candidat_cv_path_candidat_cv_entreprise_logo'),
    ]

    operations = [
    ]
