# Generated by Django 4.2 on 2025-06-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pme', '0003_remove_logo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='logo_path',
        ),
    ]
