# Generated by Django 4.2 on 2025-06-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pme', '0004_remove_entreprise_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='score_pertinence',
            field=models.FloatField(blank=True, help_text="Score de pertinence du CV par rapport à l'offre (0 à 100)", null=True),
        ),
    ]
